### ISSUE TITLE
a ripoff of discordtel

### ISSUE THREAD

**Issue by Keanu73** [SmoreSoftware/SmoreTelephony#4]
boi
you better start from scratch or we're gonna Fakin Take you Down
-owner of discordtel

**Comment by Chronomly** [comment]
*is started from nothing*

**Comment by austinhuang0131** [comment]
we mean the idea, not code

**Comment by Chronomly** [comment]
There are many music bots, many moderation bots, and many bots that are from fun. There can't be just one phone bot

**Comment by austinhuang0131** [comment]
haha yes

**Comment by Chronomly** [comment]
So uh, what is the purpose of this issue to get me to delete the bot or something?

**Comment by austinhuang0131** [comment]
just a notice kthx

**Comment by Chronomly** [comment]
That's it? Then I'm just gonna delete the issue

**Comment by austinhuang0131** [comment]
u can't delete it u can only close it :^)

**Comment by Chronomly** [comment]
per the readme
```SmoreTel is a DiscordTel alternitave with all the features of DiscordTel and more!```

**Comment by Chronomly** [comment]
Check discord

**Comment by Wist9063** [comment]
_roasted_
